.TH "Application::Scenes::CameraScene" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application::Scenes::CameraScene
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CameraScene\&.h>\fP
.PP
Inherits \fBEngine::Components::Scene\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCameraScene\fP ()"
.br
.ti -1c
.RI "\fB~CameraScene\fP ()"
.br
.ti -1c
.RI "virtual void \fBBeginLoad\fP (BaseEngine *engine)"
.br
.ti -1c
.RI "void \fBFrameUpdate\fP (\fBEngine::BaseEngine\fP *engine) override"
.br
.ti -1c
.RI "void \fBLoad\fP (\fBEngine::BaseEngine\fP *engine) override"
.br
.ti -1c
.RI "virtual void \fBSetActiveCamera\fP (Camera *camera=nullptr)"
.br
.ti -1c
.RI "virtual void \fBUnload\fP (BaseEngine *engine)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Camera * \fBActiveCamera\fP"
.br
.ti -1c
.RI "\fBGeneric::Dictionary\fP< std::string, Camera * > * \fBCameras\fP"
.br
.ti -1c
.RI "\fBGeneric::Dictionary\fP< std::string, \fBLight\fP * > * \fBLights\fP"
.br
.ti -1c
.RI "\fBGeneric::Dictionary\fP< std::string, \fBEngine::Objects::Object\fP * > * \fBObjects\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBLoaded\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float * \fBangle\fP"
.br
.ti -1c
.RI "float * \fBcolor\fP"
.br
.ti -1c
.RI "glm::mat4 * \fBmodelMatrix\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file CameraScene\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CameraScene::CameraScene ()"

.PP
Definition at line 5 of file CameraScene\&.cpp\&.
.PP
.nf
6 {
7 }
.fi
.SS "CameraScene::~CameraScene ()"

.PP
Definition at line 10 of file CameraScene\&.cpp\&.
.PP
.nf
11 {
12 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void Engine::Components::Scene::BeginLoad (\fBBaseEngine\fP * engine)\fC [virtual]\fP, \fC [inherited]\fP"

.PP
Definition at line 37 of file Scene\&.cpp\&.
.PP
Referenced by Application::Engines::CameraEngine::Init(), and Application::Engines::LightEngine::Init()\&.
.PP
.nf
38 {
39     if (!Loaded)
40     {
41         Load(engine);
42         if (ActiveCamera == nullptr)
43             SetActiveCamera();
44         Loaded = true;
45     }
46 }
.fi
.SS "void Application::Scenes::CameraScene::FrameUpdate (\fBEngine::BaseEngine\fP * engine)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEngine::Components::Scene\fP\&.
.SS "void Application::Scenes::CameraScene::Load (\fBEngine::BaseEngine\fP * engine)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEngine::Components::Scene\fP\&.
.SS "void Engine::Components::Scene::SetActiveCamera (\fBCamera\fP * camera = \fCnullptr\fP)\fC [virtual]\fP, \fC [inherited]\fP"

.PP
Definition at line 52 of file Scene\&.cpp\&.
.PP
References Engine::Components::Camera::Update()\&.
.PP
Referenced by Engine::Components::Camera::SetActive()\&.
.PP
.nf
53 {
54     if (camera == nullptr)
55         ActiveCamera = Cameras->First();
56     else
57         ActiveCamera = camera;
58     if(ActiveCamera != nullptr)
59         ActiveCamera->Update();
60 }
.fi
.SS "void Engine::Components::Scene::Unload (\fBBaseEngine\fP * engine)\fC [virtual]\fP, \fC [inherited]\fP"

.PP
Definition at line 29 of file Scene\&.cpp\&.
.PP
.nf
30 {
31     for (auto& Object : *Objects)
32         delete Object\&.second;
33     Objects->clear();
34     Loaded = false;
35 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "Camera* Engine::Components::Scene::ActiveCamera\fC [inherited]\fP"

.PP
Definition at line 30 of file Scene\&.h\&.
.PP
Referenced by Application::Input::Handlers::LightingChangeInputHandler::HandleKeys(), Application::Input::Handlers::CameraInputHandler::HandleKeys(), Application::Input::Handlers::CameraInputHandler::HandleMouse(), Application::Engines::LightEngine::Init(), and Engine::Components::Scene::Scene()\&.
.SS "float* Application::Scenes::CameraScene::angle\fC [private]\fP"

.PP
Definition at line 16 of file CameraScene\&.h\&.
.SS "\fBGeneric::Dictionary\fP<std::string, Camera*>* Engine::Components::Scene::Cameras\fC [inherited]\fP"

.PP
Definition at line 28 of file Scene\&.h\&.
.PP
Referenced by Application::Engines::CameraEngine::Init(), Application::Engines::LightEngine::Init(), and Engine::Components::Scene::Scene()\&.
.SS "float* Application::Scenes::CameraScene::color\fC [private]\fP"

.PP
Definition at line 17 of file CameraScene\&.h\&.
.SS "\fBGeneric::Dictionary\fP<std::string, \fBLight\fP*>* Engine::Components::Scene::Lights\fC [inherited]\fP"

.PP
Definition at line 29 of file Scene\&.h\&.
.PP
Referenced by Application::Input::Handlers::LightingChangeInputHandler::HandleKeys(), Application::Engines::LightEngine::Init(), and Engine::Components::Scene::Scene()\&.
.SS "bool Engine::Components::Scene::Loaded\fC [protected]\fP, \fC [inherited]\fP"

.PP
Definition at line 18 of file Scene\&.h\&.
.PP
Referenced by Engine::Components::Scene::Scene()\&.
.SS "glm::mat4* Application::Scenes::CameraScene::modelMatrix\fC [private]\fP"

.PP
Definition at line 15 of file CameraScene\&.h\&.
.SS "\fBGeneric::Dictionary\fP<std::string, \fBEngine::Objects::Object\fP*>* Engine::Components::Scene::Objects\fC [inherited]\fP"

.PP
Definition at line 27 of file Scene\&.h\&.
.PP
Referenced by Application::Input::Handlers::CameraInputHandler::HandleMouse(), Application::Engines::CameraEngine::Init(), Application::Engines::LightEngine::Init(), and Engine::Components::Scene::Scene()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
