.TH "Assets" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assets
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Assets\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const std::string \fBDirectory\fP = std::string(R'(Assets\\)')"
.br
.ti -1c
.RI "static const std::string \fBShaders\fP = std::string(R'(Assets\\Shaders\\)')"
.br
.ti -1c
.RI "static const std::string \fBShadersFragment\fP = std::string(R'(Assets\\Shaders\\Fragment\\)')"
.br
.ti -1c
.RI "static const std::string \fBShadersVertex\fP = std::string(R'(Assets\\Shaders\\Vertex\\)')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file Assets\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "const std::string Assets::Directory = std::string(R'(Assets\\)')\fC [static]\fP"

.PP
Definition at line 7 of file Assets\&.h\&.
.SS "const std::string Assets::Shaders = std::string(R'(Assets\\Shaders\\)')\fC [static]\fP"

.PP
Definition at line 8 of file Assets\&.h\&.
.SS "const std::string Assets::ShadersFragment = std::string(R'(Assets\\Shaders\\Fragment\\)')\fC [static]\fP"

.PP
Definition at line 10 of file Assets\&.h\&.
.PP
Referenced by Application::Engines::BasicEngine::Init(), Application::Engines::CameraEngine::Init(), and Application::Engines::LightEngine::Init()\&.
.SS "const std::string Assets::ShadersVertex = std::string(R'(Assets\\Shaders\\Vertex\\)')\fC [static]\fP"

.PP
Definition at line 9 of file Assets\&.h\&.
.PP
Referenced by Application::Engines::BasicEngine::Init(), Application::Engines::CameraEngine::Init(), and Application::Engines::LightEngine::Init()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
