.TH "ZPG/Assets/Models/bedna.h" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZPG/Assets/Models/bedna.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVertex\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBVertex\fP \fBVertex\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBpocetPrvku\fP =522"
.br
.ti -1c
.RI "const \fBVertex\fP \fBvertices\fP [522]"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBVertex\fP  \fBVertex\fP"

.SH "Variable Documentation"
.PP 
.SS "float pocetPrvku =522"

.PP
Definition at line 6 of file bedna\&.h\&.
.SS "const \fBVertex\fP vertices[522]"

.PP
Definition at line 8 of file bedna\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
