.TH "ZPG/Dictionary.h" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZPG/Dictionary.h
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGeneric::Dictionary< TKey, TValue >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBGeneric\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
