.TH "Engine::Components::Graphics" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Engine::Components::Graphics
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaterial\fP"
.br
.ti -1c
.RI "class \fBMaterialBindedValue\fP"
.br
.ti -1c
.RI "class \fBMaterialValue\fP"
.br
.ti -1c
.RI "class \fBMaterialValueBase\fP"
.br
.ti -1c
.RI "class \fBProgram\fP"
.br
.ti -1c
.RI "class \fBShader\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMaterialValueType\fP { \fBInt\fP, \fBFloat\fP, \fBMatrix4x4\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBEngine::Components::Graphics::MaterialValueType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIInt \fP\fP
.TP
\fB\fIFloat \fP\fP
.TP
\fB\fIMatrix4x4 \fP\fP
.PP
Definition at line 9 of file MaterialValueType\&.h\&.
.PP
.nf
10             {
11                 Int,
12                 Float,
13                 Matrix4x4
14             };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
