.TH "Generic" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Generic
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCollection\fP"
.br
.ti -1c
.RI "class \fBDictionary\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
