.TH "ZPG/MaterialValueType.h" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZPG/MaterialValueType.h
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBEngine\fP"
.br
.ti -1c
.RI " \fBEngine::Components\fP"
.br
.ti -1c
.RI " \fBEngine::Components::Graphics\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEngine::Components::Graphics::MaterialValueType\fP { \fBEngine::Components::Graphics::Int\fP, \fBEngine::Components::Graphics::Float\fP, \fBEngine::Components::Graphics::Matrix4x4\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
