.TH "ZPG/Assets/Models/2/plain.h" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZPG/Assets/Models/2/plain.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const float \fBplain\fP []"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const float plain[]"
\fBInitial value:\fP
.PP
.nf
= {
    1\&.0f, 0\&.0f,  1\&.0f, 0\&.0f, 1\&.0f, 0\&.0f,
    1\&.0f, 0\&.0f, -1\&.0f, 0\&.0f, 1\&.0f, 0\&.0f,
   -1\&.0f, 0\&.0f, -1\&.0f, 0\&.0f, 1\&.0f, 0\&.0f,

   -1\&.0f, 0\&.0f,  1\&.0f, 0\&.0f, 1\&.0f, 0\&.0f,
    1\&.0f, 0\&.0f,  1\&.0f, 0\&.0f, 1\&.0f, 0\&.0f,
   -1\&.0f, 0\&.0f, -1\&.0f, 0\&.0f, 1\&.0f, 0\&.0f

}
.fi
.PP
Definition at line 4 of file plain\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
