.TH "ZPG/Shader.h" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZPG/Shader.h
.SH SYNOPSIS
.br
.PP
\fC#include <GL/glew\&.h>\fP
.br
\fC#include <glm/vec4\&.hpp>\fP
.br
\fC#include <glm/mat4x2\&.hpp>\fP
.br
\fC#include <xstring>\fP
.br
\fC#include 'MaterialValueType\&.h'\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEngine::Components::Graphics::Shader\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBEngine\fP"
.br
.ti -1c
.RI " \fBEngine::Components\fP"
.br
.ti -1c
.RI " \fBEngine::Components::Graphics\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
