.TH "ZPG/Sphere.h" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZPG/Sphere.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Material\&.h'\fP
.br
\fC#include 'VertexAttributeObject\&.h'\fP
.br
\fC#include 'VertexObject\&.h'\fP
.br
\fC#include 'Object\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEngine::Objects::Sphere\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBEngine\fP"
.br
.ti -1c
.RI " \fBEngine::Objects\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
