.TH "ZPG/Assets/Models/2/spheref.h" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZPG/Assets/Models/2/spheref.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const float \fBsphere\fP []"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const float sphere[]"

.PP
Definition at line 5 of file spheref\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
