ZPG: Engine::Components::Camera Class Reference
Engine::Components::Camera Class Reference
#include <Camera.h>
Public Member Functions
Camera ()
~Camera ()
void Bind (Observer< Camera > &observer)
glm::mat4 * Get ()
void Notify ()
Camera * SetActive (Scene *scene)
Camera * SetDirection (glm::vec3 *direction)
Camera * SetPosition (glm::vec3 *position)
Camera * SetUp (glm::vec3 *up)
void UnBind (Observer< Camera > &observer)
Camera * Update ()
Camera * UpdateVectors ()
Public Attributes
glm::vec3 * Direction
glm::vec3 * Front
glm::vec3 * Position
glm::vec3 * Right
glm::vec3 * Up
glm::mat4 * Value
Detailed Description
Definition at line 12 of file Camera.h.
Constructor & Destructor Documentation
Camera()
Engine::Components::Camera::Camera ()
Definition at line 8 of file Camera.cpp.
References Direction, Front, Get(), Position, Right, Up, and Value.
 {
     Position = new glm::vec3(1.f, 1.f, 1.f);
     Direction = new glm::vec3(0.f, 0.f, 0.f);
     Up = new glm::vec3(0.f, 0.f, 1.f);
     Front = new glm::vec3(1.0, 1.0, 0.0);
     Right = new glm::vec3(0.0, 1.0, 1.0);
     Value = Get();
 }
~Camera()
Engine::Components::Camera::~Camera ()
Definition at line 19 of file Camera.cpp.
 {
     delete Value;
 }
Member Function Documentation
Bind()
void Observable< Camera >::Bind (Observer< Camera > & observer) inline inherited
Definition at line 19 of file Observable.h.
References Observable< T >::_observers, and Generic::Collection< T >::Add().
     {
         _observers->Add(&observer);
     }
Get()
glm::mat4 * Engine::Components::Camera::Get ()
Definition at line 24 of file Camera.cpp.
References glm::Up().
Referenced by Camera().
 {
     return new glm::mat4(lookAt(*Position, *Direction, *Up));
 }
Notify()
void Observable< Camera >::Notify () inline inherited
Definition at line 27 of file Observable.h.
References Observable< T >::_observers.
     {
         for (auto it = _observers->begin(); it != _observers->end(); ++it)
             (*it)->Update(static_cast<T*>(this));
     }
SetActive()
Engine::Components::Camera * Engine::Components::Camera::SetActive (Scene * scene)
Definition at line 72 of file Camera.cpp.
References Engine::Components::Scene::SetActiveCamera().
 {
     scene->SetActiveCamera(this);
     return this;
 }
SetDirection()
Engine::Components::Camera * Engine::Components::Camera::SetDirection (glm::vec3 * direction)
Definition at line 58 of file Camera.cpp.
 {
     *Direction = *direction;
     Update();
     return this;
 }
SetPosition()
Engine::Components::Camera * Engine::Components::Camera::SetPosition (glm::vec3 * position)
Definition at line 51 of file Camera.cpp.
 {
     *Position = *position;
     Update();
     return this;
 }
SetUp()
Engine::Components::Camera * Engine::Components::Camera::SetUp (glm::vec3 * up)
Definition at line 65 of file Camera.cpp.
References glm::Up().
 {
     *Up = *up;
     Update();
     return this;
 }
UnBind()
void Observable< Camera >::UnBind (Observer< Camera > & observer) inline inherited
Definition at line 23 of file Observable.h.
References Observable< T >::_observers.
     {
         _observers->remove(observer);
     }
Update()
Engine::Components::Camera * Engine::Components::Camera::Update ()
Definition at line 43 of file Camera.cpp.
Referenced by Application::Input::Handlers::CameraInputHandler::HandleKeys(), Application::Input::Handlers::CameraInputHandler::HandleMouse(), and Engine::Components::Scene::SetActiveCamera().
 {
     *Value = *Get();
     UpdateVectors();
     Notify();
     return this;
 }
UpdateVectors()
Engine::Components::Camera * Engine::Components::Camera::UpdateVectors ()
Up = *Position + glm::normalize(*Up - *Position); Direction = *Position + glm::normalize(*Direction - *Position);
Definition at line 29 of file Camera.cpp.
References glm::Front(), glm::Right(), and glm::Up().
 {
     /*Front->x = Direction->x;
     Front->z = Direction->z;
     Front->y = Position->y;*/
     *Front = glm::normalize(*Position - *Direction);
     *Right = glm::normalize(glm::cross(*Up, *Front));
     return this;
 }
Member Data Documentation
Direction
glm::vec3* Engine::Components::Camera::Direction
Definition at line 18 of file Camera.h.
Referenced by Camera(), Application::Input::Handlers::CameraInputHandler::HandleKeys(), and Application::Input::Handlers::CameraInputHandler::HandleMouse().
Front
glm::vec3* Engine::Components::Camera::Front
Definition at line 21 of file Camera.h.
Referenced by Camera(), and Application::Input::Handlers::CameraInputHandler::HandleKeys().
Position
glm::vec3* Engine::Components::Camera::Position
Definition at line 17 of file Camera.h.
Referenced by Camera(), Application::Input::Handlers::CameraInputHandler::HandleKeys(), and Application::Engines::LightEngine::Init().
Right
glm::vec3* Engine::Components::Camera::Right
Definition at line 20 of file Camera.h.
Referenced by Camera(), Application::Input::Handlers::CameraInputHandler::HandleKeys(), and Application::Input::Handlers::CameraInputHandler::HandleMouse().
Up
glm::vec3* Engine::Components::Camera::Up
Definition at line 19 of file Camera.h.
Referenced by Camera(), Application::Input::Handlers::CameraInputHandler::HandleKeys(), and Application::Input::Handlers::CameraInputHandler::HandleMouse().
Value
glm::mat4* Engine::Components::Camera::Value
Definition at line 29 of file Camera.h.
Referenced by Camera(), and Application::Engines::LightEngine::Init().
The documentation for this class was generated from the following files:
ZPG/Camera.h
ZPG/Camera.cpp