ZPG: Assets Class Reference
Assets Class Reference
#include <Assets.h>
Static Public Attributes
static const std::string Directory = std::string(R"(Assets\)")
static const std::string Shaders = std::string(R"(Assets\Shaders\)")
static const std::string ShadersFragment = std::string(R"(Assets\Shaders\Fragment\)")
static const std::string ShadersVertex = std::string(R"(Assets\Shaders\Vertex\)")
Detailed Description
Definition at line 4 of file Assets.h.
Member Data Documentation
Directory
const std::string Assets::Directory = std::string(R"(Assets\)") static
Definition at line 7 of file Assets.h.
Shaders
const std::string Assets::Shaders = std::string(R"(Assets\Shaders\)") static
Definition at line 8 of file Assets.h.
ShadersFragment
const std::string Assets::ShadersFragment = std::string(R"(Assets\Shaders\Fragment\)") static
Definition at line 10 of file Assets.h.
Referenced by Application::Engines::BasicEngine::Init(), Application::Engines::CameraEngine::Init(), and Application::Engines::LightEngine::Init().
ShadersVertex
const std::string Assets::ShadersVertex = std::string(R"(Assets\Shaders\Vertex\)") static
Definition at line 9 of file Assets.h.
Referenced by Application::Engines::BasicEngine::Init(), Application::Engines::CameraEngine::Init(), and Application::Engines::LightEngine::Init().
The documentation for this class was generated from the following files:
ZPG/Assets.h
ZPG/Assets.cpp