ZPG: Generic::Dictionary< TKey, TValue > Class Template Reference
Generic::Dictionary< TKey, TValue > Class Template Reference
#include <Dictionary.h>
Public Member Functions
Dictionary & Add (TKey key, TValue value)
TValue & First (TValue _default=nullptr)
TValue & Get (const TKey key, TValue _default=nullptr)
TValue & Last ()
TValue & operator[] (TKey key)
Detailed Description
template<typename TKey, class TValue>
class Generic::Dictionary< TKey, TValue >
Definition at line 7 of file Dictionary.h.
Member Function Documentation
Add()
template<typename TKey, class TValue> Dictionary& Generic::Dictionary< TKey, TValue >::Add (TKey key, TValue value) inline
Definition at line 10 of file Dictionary.h.
Referenced by Application::Input::Handlers::CameraInputHandler::HandleMouse(), and Application::Engines::LightEngine::Init().
         {
             auto pair = this->find(key);
             if (pair == this->end())
                 this->insert(std::pair<TKey, TValue>(key, value));
             else
                 pair->second = value;
             return *this;
         }
First()
template<typename TKey, class TValue> TValue& Generic::Dictionary< TKey, TValue >::First (TValue _default = nullptr) inline
Definition at line 29 of file Dictionary.h.
Referenced by Application::Input::Handlers::LightingChangeInputHandler::HandleKeys(), and Application::Engines::CameraEngine::Init().
         {
             if (this->size() == 0)
                 return _default;
             return this->begin()->second;
         }
Get()
template<typename TKey, class TValue> TValue& Generic::Dictionary< TKey, TValue >::Get (const TKey key, TValue _default = nullptr) inline
Definition at line 21 of file Dictionary.h.
Referenced by Application::Input::Handlers::CameraInputHandler::HandleMouse(), main(), and Generic::Dictionary< std::string, Engine::BaseEngine *>::operator[]().
         {
             auto r = this->find(key);
             if(r != this->end())
                 return r->second;
             return _default;
         }
Last()
template<typename TKey, class TValue> TValue& Generic::Dictionary< TKey, TValue >::Last () inline
Definition at line 36 of file Dictionary.h.
         {
             return this->end()->second;
         }
operator[]()
template<typename TKey, class TValue> TValue& Generic::Dictionary< TKey, TValue >::operator[] (TKey key) inline
Definition at line 41 of file Dictionary.h.
         {
             return Get(key);
         }
The documentation for this class was generated from the following file:
ZPG/Dictionary.h