ZPG: Application::Input::Handlers::CameraInputHandler Class Reference
Application::Input::Handlers::CameraInputHandler Class Reference
#include <CameraInputHandler.h>
Public Member Functions
CameraInputHandler ()
~CameraInputHandler ()
bool HandleKeys (Engine::BaseEngine *engine, Engine::Components::Window *window, Engine::Components::Scene *scene, Generic::Dictionary< short, bool > &keys, int keysActive) override
bool HandleMouse (Engine::BaseEngine *engine, Engine::Components::Window *window, Engine::Components::Scene *scene, double x, double y, Generic::Dictionary< short, bool > &keys, int keysActive) override
Private Attributes
glm::vec2 _lastMousePosition
float _pitch
float _yaw
Detailed Description
Definition at line 11 of file CameraInputHandler.h.
Constructor & Destructor Documentation
CameraInputHandler()
Application::Input::Handlers::CameraInputHandler::CameraInputHandler ()
Definition at line 15 of file CameraInputHandler.cpp.
References _lastMousePosition, _pitch, and _yaw.
 {
     _lastMousePosition = glm::vec2(-1, -1);
     _yaw = 0.f;
     _pitch = 0.f;
 }
~CameraInputHandler()
Application::Input::Handlers::CameraInputHandler::~CameraInputHandler () default
Member Function Documentation
HandleKeys()
bool Application::Input::Handlers::CameraInputHandler::HandleKeys (Engine::BaseEngine * engine, Engine::Components::Window * window, Engine::Components::Scene * scene, Generic::Dictionary< short, bool > & keys, int keysActive) override
Definition at line 25 of file CameraInputHandler.cpp.
References Engine::Components::Scene::ActiveCamera, Engine::Components::Camera::Direction, Engine::Components::Camera::Front, Engine::Components::Camera::Position, Engine::Components::Camera::Right, Engine::Components::Camera::Up, and Engine::Components::Camera::Update().
 {
     const float speed = 0.2f;
     glm::vec3 change = glm::vec3(0);
     if (keys['W'])
          change -= *(scene->ActiveCamera->Front) * speed;
     if (keys['S'])
         change += *(scene->ActiveCamera->Front) * speed;
     if (keys['A'])
         change -= *(scene->ActiveCamera->Right) * speed;
     if (keys['D'])
         change += *(scene->ActiveCamera->Right) * speed;
     if (keys['E'])
         change -= *(scene->ActiveCamera->Up) * speed;
     if (keys['Q'])
         change += *(scene->ActiveCamera->Up) * speed;
     if (change != glm::vec3(0))
     {
         *(scene->ActiveCamera->Position) += change;
         *(scene->ActiveCamera->Direction) += change;
         scene->ActiveCamera->Update();
     }
     return true;
 }
HandleMouse()
bool Application::Input::Handlers::CameraInputHandler::HandleMouse (Engine::BaseEngine * engine, Engine::Components::Window * window, Engine::Components::Scene * scene, double x, double y, Generic::Dictionary< short, bool > & keys, int keysActive) override
Definition at line 53 of file CameraInputHandler.cpp.
References Engine::Components::Scene::ActiveCamera, Generic::Dictionary< TKey, TValue >::Add(), Engine::Components::Camera::Direction, Generic::Dictionary< TKey, TValue >::Get(), Engine::Components::Window::Height, MK_R, Engine::Components::Scene::Objects, Engine::BaseEngine::Programs, Engine::Components::Camera::Right, Engine::BaseEngine::Shaders, sphere, Engine::Components::Camera::Up, Engine::Components::Camera::Update(), Engine::Components::Graphics::Material::Values, and Engine::Components::Window::Width.
 {
     if (_lastMousePosition.x < 0)
     {
         _lastMousePosition.x = x;
         _lastMousePosition.y = y;
     }
     // Allow Move mouse without camera change
     if (keys[MK_R])
     {
         auto fow = glm::radians(90.f);
         const float sensitivity = 10.f;
         auto diff = glm::vec2(x, y) - _lastMousePosition;
         diff.x = diff.x * sensitivity * fow / static_cast<float>(window->Width);
         diff.y = diff.y * sensitivity * fow / static_cast<float>(window->Height);
         fprintf(stderr, "Diff: %f, %f\t", diff.x, diff.y);
         if (diff.x != 0 || diff.y != 0)
         {
             *(scene->ActiveCamera->Direction) += *(scene->ActiveCamera->Right) * diff.x;
             *(scene->ActiveCamera->Direction) -= *(scene->ActiveCamera->Up) * diff.y;
             scene->ActiveCamera->Update();
         }
     }
     // Draw look point
     auto name = "target";
     auto obj = scene->Objects->Get(name);
     if (obj == nullptr)
     {
         auto mat = new Engine::Components::Graphics::Material(engine->Programs->Get("basic"));
         mat->Values->Add(new Engine::Components::Graphics::MaterialValue<glm::vec4>(
             engine->Shaders->Get("fragment"), "color", new glm::vec4(255.f, 0.f, 0.f, 1.f)
         )).Add(new Engine::Components::Graphics::MaterialValue<bool>(
             engine->Shaders->Get("fragment"), "useLighting", new bool(false)
         ));
         const auto object = new Engine::Objects::Sphere(mat, sphere, 17280, 3);
         *(object->ModelMatrix) = glm::scale(glm::translate(glm::mat4(1.f), *scene->ActiveCamera->Direction), glm::vec3(0.1f, 0.1f, 0.1f));
         scene->Objects->Add(name, object);
     }
     else
     {
         *(obj->ModelMatrix) = glm::scale(glm::translate(glm::mat4(1.f), *scene->ActiveCamera->Direction), glm::vec3(0.1f, 0.1f, 0.1f));
     }
     _lastMousePosition.x = x;
     _lastMousePosition.y = y;
     return true;
 }
Member Data Documentation
_lastMousePosition
glm::vec2 Application::Input::Handlers::CameraInputHandler::_lastMousePosition private
Definition at line 14 of file CameraInputHandler.h.
Referenced by CameraInputHandler().
_pitch
float Application::Input::Handlers::CameraInputHandler::_pitch private
Definition at line 15 of file CameraInputHandler.h.
Referenced by CameraInputHandler().
_yaw
float Application::Input::Handlers::CameraInputHandler::_yaw private
Definition at line 16 of file CameraInputHandler.h.
Referenced by CameraInputHandler().
The documentation for this class was generated from the following files:
ZPG/CameraInputHandler.h
ZPG/CameraInputHandler.cpp