ZPG: Engine::Components::Graphics::Shader Class Reference
Engine::Components::Graphics::Shader Class Reference
#include <Shader.h>
Public Member Functions
Shader (int type, std::string filename)
Shader (int type, const char *shader)
~Shader ()
Shader * Compile ()
GLuint * Get ()
Shader * SendUniform (Program *program, const GLchar *name, glm::mat4 *data)
Shader * SendUniform (Program *program, const GLchar *name, glm::vec4 *data)
Shader * SendUniform (Program *program, const GLchar *name, glm::vec3 *data)
Shader * SendUniform (Program *program, const GLchar *name, float *data)
Shader * SendUniform (Program *program, const GLchar *name, int *data)
Shader * SendUniform (Program *program, const GLchar *name, bool *data)
void setData (Program *program, const GLchar *property, MaterialValueType type, void *value)
Private Member Functions
std::string Mat4ToString (glm::mat4 &mat)
Private Attributes
char * _code
bool _compiled
GLuint _shader
Detailed Description
Definition at line 18 of file Shader.h.
Constructor & Destructor Documentation
Shader() [1/2]
Engine::Components::Graphics::Shader::Shader (int type, std::string filename)
Definition at line 13 of file Shader.cpp.
References _compiled, and _shader.
 {
     _compiled = false;
     std::ifstream file(filename, std::ios::in);
     if (file.is_open())
     {
         std::stringstream buffer;
         buffer << file.rdbuf();
         std::string sh = buffer.str();
         file.close();
         const auto version = sh.find_first_of('#');
         sh = sh.substr(version, sh.length() - version);
         const char* shader = sh.data();
         _shader = glCreateShader(type);
         glShaderSource(_shader, 1, &shader, NULL);
         glCompileShader(_shader);
         /*
         // Handle Error
         GLint isCompiled = 0;
         glGetShaderiv(_shader, GL_COMPILE_STATUS, &isCompiled);
         if (isCompiled == GL_FALSE)
         {
             GLint maxLength = 0;
             glGetShaderiv(_shader, GL_INFO_LOG_LENGTH, &maxLength);
             std::vector<GLchar> errorLog(maxLength);
             glGetShaderInfoLog(_shader, maxLength, &maxLength, &errorLog[0]);
             fprintf(stderr, "Shader %u Compilation failed:\nCode:\n%s\nErrors:\n%s\n", _shader, shader, errorLog.data());
         }
         _compiled = isCompiled != GL_FALSE;*/
     }
 }
Shader() [2/2]
Engine::Components::Graphics::Shader::Shader (int type, const char * shader)
Definition at line 49 of file Shader.cpp.
 {
     _shader = glCreateShader(type);
     glShaderSource(_shader, 1, &shader, NULL);
 }
~Shader()
Engine::Components::Graphics::Shader::~Shader ()
Definition at line 55 of file Shader.cpp.
 {
     /*delete _code;
     delete &_compiled;
     delete &_shader;*/
 }
Member Function Documentation
Compile()
Engine::Components::Graphics::Shader * Engine::Components::Graphics::Shader::Compile ()
Definition at line 62 of file Shader.cpp.
 {
     glCompileShader(_shader);
     GLint isCompiled = 0;
     glGetShaderiv(_shader, GL_COMPILE_STATUS, &isCompiled);
     if (isCompiled == GL_FALSE)
     {
         GLint maxLength = 0;
         glGetShaderiv(_shader, GL_INFO_LOG_LENGTH, &maxLength);
         // The maxLength includes the NULL character
         std::vector<GLchar> errorLog(maxLength);
         glGetShaderInfoLog(_shader, maxLength, &maxLength, &errorLog[0]);
         fprintf(stderr, "Shader %u Compilation failed:\nCode:\n%s\nErrors:\n%s\n", _shader, _code, errorLog.data());
     }
     _compiled = isCompiled != GL_FALSE;
     return this;
 }
Get()
GLuint * Engine::Components::Graphics::Shader::Get ()
Definition at line 82 of file Shader.cpp.
Referenced by Engine::Components::Graphics::Program::AddShader().
 {
     if (!_compiled)
         Compile();
     return &_shader;
 }
Mat4ToString()
std::string Engine::Components::Graphics::Shader::Mat4ToString (glm::mat4 & mat) private
Definition at line 202 of file Shader.cpp.
 {
     char* txt = new char[200];
     sprintf_s(txt, 200, "%6.4f\t%6.4f\t%6.4f\t%6.4f\n%6.4f\t%6.4f\t%6.4f\t%6.4f\n%6.4f\t%6.4f\t%6.4f\t%6.4f\n%6.4f\t%6.4f\t%6.4f\t%6.4f",
         mat[0][0], mat[0][1], mat[0][2], mat[0][3],
         mat[1][0], mat[1][1], mat[1][2], mat[1][3],
         mat[2][0], mat[2][1], mat[2][2], mat[2][3],
         mat[3][0], mat[3][1], mat[3][2], mat[3][3]);
     /*txt << mat[0][0] << "\t\t" << mat[0][1] << "\t\t" << mat[0][2] << "\t\t" << mat[0][3] << std::endl;
     txt << mat[1][0] << "\t\t" << mat[1][1] << "\t\t" << mat[1][2] << "\t\t" << mat[1][3] << std::endl;
     txt << mat[2][0] << "\t\t" << mat[2][1] << "\t\t" << mat[2][2] << "\t\t" << mat[2][3] << std::endl;
     txt << mat[3][0] << "\t\t" << mat[3][1] << "\t\t" << mat[3][2] << "\t\t" << mat[3][3] << std::endl;*/
     return std::string(txt);
 }
SendUniform() [1/6]
Engine::Components::Graphics::Shader * Engine::Components::Graphics::Shader::SendUniform (Program * program, const GLchar * name, glm::mat4 * data)
Definition at line 89 of file Shader.cpp.
References Engine::Components::Graphics::Program::Get().
Referenced by Engine::Components::Graphics::MaterialValue< T >::Set().
 {
     #ifdef DEBUG
         fprintf(stderr, "SET MAT4: %s (0x%p) value \n%s\n", name, data, Mat4ToString(*data).c_str());
     #endif
     GLint uniformID = glGetUniformLocation(*(program->Get()), name);
     if (uniformID >= 0) {
         glUniformMatrix4fv(uniformID, 1, GL_FALSE, value_ptr(*data));
     }
     else {
         fprintf(stderr, "ERROR: program 0x%p:%u mat4 variable %s not found\n", program, *(program->Get()), name);
     }
     return this;
 }
SendUniform() [2/6]
Engine::Components::Graphics::Shader * Engine::Components::Graphics::Shader::SendUniform (Program * program, const GLchar * name, glm::vec4 * data)
Definition at line 105 of file Shader.cpp.
References Engine::Components::Graphics::Program::Get().
 {
     #ifdef DEBUG
         fprintf(stderr, "SET VEC4: %s (0x%p) value \n(%f, %f, %f, %f)\n", name, data, data->x, data->y, data->z, data->w);
     #endif
     GLint uniformID = glGetUniformLocation(*(program->Get()), name);
     if (uniformID >= 0) {
         glUniform4f(uniformID, data->x, data->y, data->z, data->w);
     }
     else {
         fprintf(stderr, "ERROR: program 0x%p:%u vec4 variable %s not found\n", program, *(program->Get()), name);
     }
     return this;
 }
SendUniform() [3/6]
Engine::Components::Graphics::Shader * Engine::Components::Graphics::Shader::SendUniform (Program * program, const GLchar * name, glm::vec3 * data)
Definition at line 121 of file Shader.cpp.
References Engine::Components::Graphics::Program::Get().
 {
     #ifdef DEBUG
         fprintf(stderr, "SET VEC3: %s (0x%p) value \n(%f, %f, %f)\n", name, data, data->x, data->y, data->z);
     #endif
     GLint uniformID = glGetUniformLocation(*(program->Get()), name);
     if (uniformID >= 0) {
         glUniform3f(uniformID, data->x,data->y,data->z);
     }
     else {
         fprintf(stderr, "ERROR: program 0x%p:%u vec3 variable %s not found\n", program, *(program->Get()), name);
     }
     return this;
 }
SendUniform() [4/6]
Engine::Components::Graphics::Shader * Engine::Components::Graphics::Shader::SendUniform (Program * program, const GLchar * name, float * data)
Definition at line 138 of file Shader.cpp.
References Engine::Components::Graphics::Program::Get().
 {
     #ifdef DEBUG
         fprintf(stderr, "SET FLOAT: %s (0x%x) value %f\n", name, data, *data);
     #endif
     GLint uniformID = glGetUniformLocation(*(program->Get()), name);
     if (uniformID >= 0) {
         glUniform1f(uniformID, *data);
     }
     else {
         fprintf(stderr, "ERROR: program 0x%p:%u float variable %s not found\n", program, *(program->Get()), name);
     }
     return this;
 }
SendUniform() [5/6]
Engine::Components::Graphics::Shader * Engine::Components::Graphics::Shader::SendUniform (Program * program, const GLchar * name, int * data)
Definition at line 154 of file Shader.cpp.
References Engine::Components::Graphics::Program::Get().
 {
     #ifdef DEBUG
         fprintf(stderr, "SET INT: %s (0x%p) value %d\n", name, data, *data);
     #endif
     GLint uniformID = glGetUniformLocation(*(program->Get()), name);
     if (uniformID >= 0) {
         glUniform1i(uniformID, *data);
     }
     else {
         fprintf(stderr, "ERROR: program 0x%p:%u int variable %s not found\n", program, *(program->Get()), name);
     }
     return this;
 }
SendUniform() [6/6]
Engine::Components::Graphics::Shader * Engine::Components::Graphics::Shader::SendUniform (Program * program, const GLchar * name, bool * data)
Definition at line 170 of file Shader.cpp.
References Engine::Components::Graphics::Program::Get().
 {
     #ifdef DEBUG
         fprintf(stderr, "SET BOOL: %s (0x%p) value %b\n", name, data, *data);
     #endif
     GLint uniformID = glGetUniformLocation(*(program->Get()), name);
     if (uniformID >= 0) {
         glUniform1i(uniformID, *data);
     }
     else {
         fprintf(stderr, "ERROR: program 0x%p:%u int variable %s not found\n", program, *(program->Get()), name);
     }
     return this;
 }
setData()
void Engine::Components::Graphics::Shader::setData (Program * program, const GLchar * property, MaterialValueType type, void * value)
Definition at line 186 of file Shader.cpp.
References Engine::Components::Graphics::Float, Engine::Components::Graphics::Int, and Engine::Components::Graphics::Matrix4x4.
 {
     switch (type)
     {
         case Int:
             SendUniform(program, property, static_cast<int*>(value));
             break;
         case Float:
             SendUniform(program, property, static_cast<float*>(value));
             break;
         case Matrix4x4:
             SendUniform(program, property, static_cast<glm::mat4*>(value));
             break;
     }
 }
Member Data Documentation
_code
char* Engine::Components::Graphics::Shader::_code private
Definition at line 36 of file Shader.h.
_compiled
bool Engine::Components::Graphics::Shader::_compiled private
Definition at line 35 of file Shader.h.
Referenced by Shader().
_shader
GLuint Engine::Components::Graphics::Shader::_shader private
Definition at line 34 of file Shader.h.
Referenced by Shader().
The documentation for this class was generated from the following files:
ZPG/Shader.h
ZPG/Shader.cpp