ZPG: glm Namespace Reference
glm Namespace Reference
Functions
vec3 Back (0, 0, 1)
vec3 Down (0, -1, 0)
vec3 Front (0, 0, -1)
vec3 Left (-1, 0, 0)
vec3 Right (1, 0, 0)
vec2 rotateAround (vec2 center, vec2 point, float angle)
float simplify (float vector, float value=1.f)
vec3 simplify (glm::vec3 vector, float value=1.f)
vec2 simplify (glm::vec2 vector, float value=1.f)
vec3 Up (0, 1, 0)
Function Documentation
Back()
vec3 glm::Back (0 , 0 , 1)
Down()
vec3 glm::Down (0 , - 1, 0)
Front()
vec3 glm::Front (0 , 0 , - 1)
Referenced by Engine::Components::Camera::UpdateVectors().
Left()
vec3 glm::Left (- 1, 0 , 0)
Right()
vec3 glm::Right (1 , 0 , 0)
Referenced by Engine::Components::Camera::UpdateVectors().
rotateAround()
vec2 glm::rotateAround (vec2 center, vec2 point, float angle) inline
Definition at line 32 of file gmlExtensions.h.
{
         return vec2(cos(angle) * (point.x - center.x) - sin(angle) * (point.y - center.y) + center.x,
                     sin(angle) * (point.x - center.x) + cos(angle) * (point.y - center.y) + center.y);
     }
simplify() [1/3]
float glm::simplify (float vector, float value = 1.f) inline
Definition at line 7 of file gmlExtensions.h.
Referenced by simplify().
     {
         if (vector > 0)
             return value;
         if (vector < 0)
             return -value;
         return 0.f;
     }
simplify() [2/3]
vec3 glm::simplify (glm::vec3 vector, float value = 1.f) inline
Definition at line 16 of file gmlExtensions.h.
References simplify().
     {
         auto v = vector;
         v.x = simplify(v.x,value);
         v.y = simplify(v.y, value);
         v.z = simplify(v.z, value);
         return v;
     }
simplify() [3/3]
vec2 glm::simplify (glm::vec2 vector, float value = 1.f) inline
Definition at line 24 of file gmlExtensions.h.
References simplify().
     {
         auto v = vector;
         v.x = simplify(v.x, value);
         v.y = simplify(v.y, value);
         return v;
     }
Up()
vec3 glm::Up (0 , 1 , 0)
Referenced by Engine::Components::Camera::Get(), Engine::Components::Camera::SetUp(), and Engine::Components::Camera::UpdateVectors().