.TH "Engine::Objects::Object" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Engine::Objects::Object
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Object\&.h>\fP
.PP
Inherits \fBEngine::Components::Objects::VertexObject\fP\&.
.PP
Inherited by \fBEngine::Objects::Sphere\fP, and \fBLight\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObject\fP (\fBComponents::Graphics::Material\fP *material, const float *points, int size, int dimensions=3, int startArrayIndex=0)"
.br
.ti -1c
.RI "\fBObject\fP (\fBComponents::Graphics::Material\fP *material, const float *points, int size, int dimensions, \fBGeneric::Collection\fP< \fBComponents::Objects::VAOConfig\fP *> configs)"
.br
.ti -1c
.RI "\fB~Object\fP ()"
.br
.ti -1c
.RI "\fBVertexObject\fP * \fBDraw\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Graphics::Material * \fBMaterial\fP"
.br
.ti -1c
.RI "glm::mat4 * \fBModelMatrix\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBVertexObject\fP * \fBAdd\fP (int size, int offset)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fB_attribute_id\fP"
.br
.ti -1c
.RI "int \fB_Id\fP"
.br
.ti -1c
.RI "GLuint \fB_VAO\fP = 0"
.br
.ti -1c
.RI "GLuint \fB_VBO\fP = 0"
.br
.ti -1c
.RI "int \fBDimensions\fP"
.br
.ti -1c
.RI "int \fBSize\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static int \fB_object_id\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file Object\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Engine::Objects::Object::Object (\fBComponents::Graphics::Material\fP * material, const float * points, int size, int dimensions = \fC3\fP, int startArrayIndex = \fC0\fP)"

.PP
Definition at line 4 of file Object\&.cpp\&.
.PP
References Engine::Components::Objects::VertexObject::Material, ModelMatrix, Engine::Components::Graphics::Material::Program, Engine::Components::Graphics::Program::Shaders, and Engine::Components::Graphics::Material::Values\&.
.PP
.nf
4                                                                                                                                    : 
5     VertexObject(material, points, size, dimensions, &((new Generic::Collection<Components::Objects::VAOConfig*>())
6         ->Add(new Engine::Components::Objects::VAOConfig(0, startArrayIndex))
7     ))
8 {
9     ModelMatrix = new glm::mat4(1\&.f);
10     Material->Values->Add(new Engine::Components::Graphics::MaterialValue<glm::mat4>(
11         Material->Program->Shaders->Get("vertex"), "modelMatrix", ModelMatrix
12     ));
13 }
.fi
.SS "Engine::Objects::Object::Object (\fBComponents::Graphics::Material\fP * material, const float * points, int size, int dimensions, \fBGeneric::Collection\fP< \fBComponents::Objects::VAOConfig\fP *> configs)"

.PP
Definition at line 15 of file Object\&.cpp\&.
.PP
References Engine::Components::Objects::VertexObject::Material, ModelMatrix, Engine::Components::Graphics::Material::Program, Engine::Components::Graphics::Program::Shaders, and Engine::Components::Graphics::Material::Values\&.
.PP
.nf
15                                                                                                                                                                        :
16     VertexObject(material, points, size, dimensions, &configs)
17 {
18     ModelMatrix = new glm::mat4(1\&.f);
19     Material->Values->Add(new Engine::Components::Graphics::MaterialValue<glm::mat4>(
20         Material->Program->Shaders->Get("vertex"), "modelMatrix", ModelMatrix
21     ));
22 }
.fi
.SS "Engine::Objects::Object::~Object ()\fC [default]\fP"

.PP
Referenced by Engine::Objects::Sphere::~Sphere()\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBEngine::Components::Objects::VertexObject\fP * Engine::Components::Objects::VertexObject::Add (int size, int offset)\fC [protected]\fP, \fC [inherited]\fP"

.PP
Definition at line 6 of file VertexObject\&.cpp\&.
.PP
References Engine::Components::Objects::VertexObject::_attribute_id, and Engine::Components::Objects::VertexObject::Dimensions\&.
.PP
.nf
7 {
8 
9     /*glEnableVertexAttribArray(_attribute_id); //enable vertex attributes
10     glBindBuffer(GL_ARRAY_BUFFER, _VBO);
11     glVertexAttribPointer(_attribute_id++, *Dimensions, GL_FLOAT, GL_FALSE, size * sizeof(float), (GLvoid*)offset);*/
12     glEnableVertexAttribArray(_attribute_id);
13     glVertexAttribPointer(_attribute_id, Dimensions, GL_FLOAT, GL_FALSE, size, (void*)offset);
14     _attribute_id++;
15     //VAOs->Add(new VertexAttributeObject(VAOi++, VBO, *Dimensions, size, offset));
16     return this;
17 }
.fi
.SS "\fBEngine::Components::Objects::VertexObject\fP * Engine::Components::Objects::VertexObject::Draw ()\fC [inherited]\fP"

.PP
Definition at line 76 of file VertexObject\&.cpp\&.
.PP
Referenced by Engine::Objects::Sphere::Draw()\&.
.PP
.nf
77 {
78     // use material
79     Material->Use();
80 
81 
82     glBindVertexArray(_VAO);
83     // draw triangles
84     glDrawArrays(GL_TRIANGLES, 0, Size);
85     return this;
86 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "int Engine::Components::Objects::VertexObject::_attribute_id\fC [protected]\fP, \fC [inherited]\fP"

.PP
Definition at line 24 of file VertexObject\&.h\&.
.PP
Referenced by Engine::Components::Objects::VertexObject::Add()\&.
.SS "int Engine::Components::Objects::VertexObject::_Id\fC [protected]\fP, \fC [inherited]\fP"

.PP
Definition at line 23 of file VertexObject\&.h\&.
.SS "int Engine::Components::Objects::VertexObject::_object_id = 0\fC [static]\fP, \fC [protected]\fP, \fC [inherited]\fP"

.PP
Definition at line 26 of file VertexObject\&.h\&.
.SS "GLuint Engine::Components::Objects::VertexObject::_VAO = 0\fC [protected]\fP, \fC [inherited]\fP"

.PP
Definition at line 22 of file VertexObject\&.h\&.
.SS "GLuint Engine::Components::Objects::VertexObject::_VBO = 0\fC [protected]\fP, \fC [inherited]\fP"

.PP
Definition at line 21 of file VertexObject\&.h\&.
.SS "int Engine::Components::Objects::VertexObject::Dimensions\fC [protected]\fP, \fC [inherited]\fP"

.PP
Definition at line 20 of file VertexObject\&.h\&.
.PP
Referenced by Engine::Components::Objects::VertexObject::Add()\&.
.SS "Graphics::Material* Engine::Components::Objects::VertexObject::Material\fC [inherited]\fP"

.PP
Definition at line 32 of file VertexObject\&.h\&.
.PP
Referenced by Application::Engines::CameraEngine::Init(), Light::Light(), and Object()\&.
.SS "glm::mat4* Engine::Objects::Object::ModelMatrix"

.PP
Definition at line 11 of file Object\&.h\&.
.PP
Referenced by Application::Input::Handlers::LightingChangeInputHandler::HandleKeys(), Light::Light(), and Object()\&.
.SS "int Engine::Components::Objects::VertexObject::Size\fC [protected]\fP, \fC [inherited]\fP"

.PP
Definition at line 25 of file VertexObject\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
