.TH "IInputHandler" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IInputHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBApplication::Input::Handlers::CameraInputHandler\fP, and \fBEngine::Components::BaseInputHandler\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
