.TH "Engine::Components::Objects::VAOConfig" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Engine::Components::Objects::VAOConfig
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VertexObject\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVAOConfig\fP ()"
.br
.ti -1c
.RI "\fBVAOConfig\fP (int size, int offset)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBOffset\fP"
.br
.ti -1c
.RI "int \fBSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file VertexObject\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Engine::Components::Objects::VAOConfig::VAOConfig ()"

.PP
Definition at line 88 of file VertexObject\&.cpp\&.
.PP
.nf
88                                             : Size(0), Offset(0)
89 {
90 }
.fi
.SS "Engine::Components::Objects::VAOConfig::VAOConfig (int size, int offset)"

.PP
Definition at line 92 of file VertexObject\&.cpp\&.
.PP
.nf
92                                                                 : Size(size), Offset(offset)
93 {
94 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "int Engine::Components::Objects::VAOConfig::Offset"

.PP
Definition at line 41 of file VertexObject\&.h\&.
.SS "int Engine::Components::Objects::VAOConfig::Size"

.PP
Definition at line 40 of file VertexObject\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
