.TH "ZPG/gmlExtensions.h" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZPG/gmlExtensions.h
.SH SYNOPSIS
.br
.PP
\fC#include <glm/vec3\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "vec3 \fBglm::Back\fP (0, 0, 1)"
.br
.ti -1c
.RI "vec3 \fBglm::Down\fP (0, \-1, 0)"
.br
.ti -1c
.RI "vec3 \fBglm::Front\fP (0, 0, \-1)"
.br
.ti -1c
.RI "vec3 \fBglm::Left\fP (\-1, 0, 0)"
.br
.ti -1c
.RI "vec3 \fBglm::Right\fP (1, 0, 0)"
.br
.ti -1c
.RI "vec2 \fBglm::rotateAround\fP (vec2 center, vec2 point, float angle)"
.br
.ti -1c
.RI "float \fBglm::simplify\fP (float vector, float value=1\&.f)"
.br
.ti -1c
.RI "vec3 \fBglm::simplify\fP (glm::vec3 vector, float value=1\&.f)"
.br
.ti -1c
.RI "vec2 \fBglm::simplify\fP (glm::vec2 vector, float value=1\&.f)"
.br
.ti -1c
.RI "vec3 \fBglm::Up\fP (0, 1, 0)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
