.TH "ZPG/MaterialValue.h" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZPG/MaterialValue.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'Shader\&.h'\fP
.br
\fC#include 'MaterialValueType\&.h'\fP
.br
\fC#include 'MaterialValueBase\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEngine::Components::Graphics::MaterialValue< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBEngine\fP"
.br
.ti -1c
.RI " \fBEngine::Components\fP"
.br
.ti -1c
.RI " \fBEngine::Components::Graphics\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
