.TH "ZPG/Assets/Models/suzi_smooth.h" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZPG/Assets/Models/suzi_smooth.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVertex\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBVertex\fP \fBVertex\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBpocetPrvku\fP =2904"
.br
.ti -1c
.RI "const \fBVertex\fP \fBvertices\fP [2904]"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBVertex\fP  \fBVertex\fP"

.SH "Variable Documentation"
.PP 
.SS "float pocetPrvku =2904"

.PP
Definition at line 6 of file suzi_smooth\&.h\&.
.SS "const \fBVertex\fP vertices[2904]"

.PP
Definition at line 8 of file suzi_smooth\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
