.TH "Vertex" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vertex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bedna\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBNormal\fP [3]"
.br
.ti -1c
.RI "float \fBPosition\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file bedna\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float Vertex::Normal"

.PP
Definition at line 4 of file bedna\&.h\&.
.SS "float Vertex::Position"

.PP
Definition at line 3 of file bedna\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
