.TH "ZPG/Window.cpp" 3 "Sat Nov 3 2018" "Version 4.0" "ZPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZPG/Window.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include 'Window\&.h'\fP
.br
\fC#include <glm/mat4x2\&.hpp>\fP
.br
\fC#include <glm/ext/quaternion_trigonometric\&.inl>\fP
.br
\fC#include <glm/ext/matrix_transform\&.inl>\fP
.br
\fC#include <ostream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for ZPG from the source code\&.
